"""adicionando coluna observacao2

Revision ID: 0486c210b195
Revises: 
Create Date: 2025-08-24 12:44:25.792257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0486c210b195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao2', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloco', schema=None) as batch_op:
        batch_op.drop_column('observacao2')

    # ### end Alembic commands ###
