"""Adicioanada opção de ATIVO na tabela componentes

Revision ID: 1268901aaf4d
Revises: e2a065da4173
Create Date: 2025-09-27 15:40:02.719187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1268901aaf4d'
down_revision = 'e2a065da4173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
