"""Adiicionada a tabela estoque

Revision ID: 387bb7be064a
Revises: c502bb808727
Create Date: 2025-09-28 17:34:02.553657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387bb7be064a'
down_revision = 'c502bb808727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('componente_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['componente_id'], ['componente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque')
    # ### end Alembic commands ###
