"""Criar tabela Movimentacao

Revision ID: c502bb808727
Revises: 1268901aaf4d
Create Date: 2025-09-28 11:19:10.281826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c502bb808727'
down_revision = '1268901aaf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('componente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('producao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['componente_id'], ['componente.id'], ),
    sa.ForeignKeyConstraint(['producao_id'], ['producao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    # ### end Alembic commands ###
