"""Criando tabelas Componente e Producao

Revision ID: e2a065da4173
Revises: 
Create Date: 2025-09-27 10:49:20.471037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a065da4173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producao_id', sa.String(length=50), nullable=False),
    sa.Column('data_producao', sa.Date(), nullable=False),
    sa.Column('tipo_espuma', sa.String(length=50), nullable=False),
    sa.Column('densidade_real', sa.Float(), nullable=False),
    sa.Column('conformidade', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producao_id')
    )
    op.create_table('componenteproducao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producao_id', sa.Integer(), nullable=False),
    sa.Column('componente_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_usada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['componente_id'], ['componente.id'], ),
    sa.ForeignKeyConstraint(['producao_id'], ['producao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('componenteproducao')
    op.drop_table('producao')
    op.drop_table('componente')
    # ### end Alembic commands ###
